using Rhino.Geometry;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace EddyLib
{
    public class STLExport
    {
        public static void ExportASCI(string filePath, List<Mesh> meshObjects)
        {
            var dir = Path.GetDirectoryName(filePath);
            if (dir != null && !Directory.Exists(dir)) Directory.CreateDirectory(dir);

            // Bolt: Replaced StringBuilder with StreamWriter to stream directly to disk,
            // preventing LOH allocations and OOM exceptions on large datasets.
            using var sw = new StreamWriter(filePath, false, Encoding.ASCII, 65536);
            sw.WriteLine("solid OBJECT");

            foreach (Mesh m in meshObjects)
            {
                m.Faces.ConvertQuadsToTriangles();   // STL supports trinangles only!

                m.FaceNormals.ComputeFaceNormals();

                for (int i = 0; i < m.Faces.Count; i++)
                {
                    var pt1 = m.Vertices[m.Faces[i].A];
                    var pt2 = m.Vertices[m.Faces[i].B];
                    var pt3 = m.Vertices[m.Faces[i].C];

                    sw.Write("\tfacet normal ");
                    Utilities.WritePV(sw, m.FaceNormals[i]);
                    sw.WriteLine();
                    sw.WriteLine("\t\touter loop");
                    sw.Write("\t\t\tvertex ");
                    Utilities.WritePV(sw, pt1);
                    sw.WriteLine();
                    sw.Write("\t\t\tvertex ");
                    Utilities.WritePV(sw, pt2);
                    sw.WriteLine();
                    sw.Write("\t\t\tvertex ");
                    Utilities.WritePV(sw, pt3);
                    sw.WriteLine();
                    sw.WriteLine("\t\tendloop");
                    sw.WriteLine("\tendfacet");
                }
            }

            sw.WriteLine("endsolid OBJECT");
        }

        public static void ExportASCI(string filePath, Mesh m)
        {
            var dir = Path.GetDirectoryName(filePath);
            if (dir != null && !Directory.Exists(dir)) Directory.CreateDirectory(dir);

            // Bolt: Replaced StringBuilder with StreamWriter to stream directly to disk,
            // preventing LOH allocations and OOM exceptions on large datasets.
            using var sw = new StreamWriter(filePath, false, Encoding.ASCII, 65536);
            sw.WriteLine("solid OBJECT");

            m.Faces.ConvertQuadsToTriangles();   // STL supports trinangles only!

            m.FaceNormals.ComputeFaceNormals();

            for (int i = 0; i < m.Faces.Count; i++)
            {
                var pt1 = m.Vertices[m.Faces[i].A];
                var pt2 = m.Vertices[m.Faces[i].B];
                var pt3 = m.Vertices[m.Faces[i].C];

                sw.Write("\tfacet normal ");
                Utilities.WritePV(sw, m.FaceNormals[i]);
                sw.WriteLine();
                sw.WriteLine("\t\touter loop");
                sw.Write("\t\t\tvertex ");
                Utilities.WritePV(sw, pt1);
                sw.WriteLine();
                sw.Write("\t\t\tvertex ");
                Utilities.WritePV(sw, pt2);
                sw.WriteLine();
                sw.Write("\t\t\tvertex ");
                Utilities.WritePV(sw, pt3);
                sw.WriteLine();
                sw.WriteLine("\t\tendloop");
                sw.WriteLine("\tendfacet");
            }

            sw.WriteLine("endsolid OBJECT");
        }

        public static void ExportASCII(string filePath, List<Mesh> meshObjects)
        {
            //triangulate, compute face normals and count facets
            int faceCnt = 0;
            foreach (Mesh m in meshObjects)
            {
                m.Faces.ConvertQuadsToTriangles();   // STL supports trinangles only!
                m.FaceNormals.ComputeFaceNormals();
                faceCnt += m.Faces.Count;
            }

            // Use using statement and File.Open.
            using (BinaryWriter b = new BinaryWriter(
                File.Open(filePath, FileMode.Create)))
            {
                byte[] header = Encoding.ASCII.GetBytes("Binary STL generated by Eddy3D" + EddyLib.EddyVersion.ProductVersion);
                byte[] headerFull = new byte[80];
                Buffer.BlockCopy(header, 0, headerFull, 0, Math.Min(header.Length, headerFull.Length));

                b.Write(headerFull);
                b.Write((UInt32)faceCnt);

                UInt16 AttributeByteCount = 0; //After these follows a 2-byte ("short") unsigned integer that is the "attribute byte count" – in the standard format, this should be zero because most software does not understand anything else.

                foreach (Mesh m in meshObjects)
                {
                    for (int i = 0; i < m.Faces.Count; i++)
                    {
                        var pt1 = m.Vertices[m.Faces[i].A];
                        var pt2 = m.Vertices[m.Faces[i].B];
                        var pt3 = m.Vertices[m.Faces[i].C];

                        b.Write((float)m.FaceNormals[i].X);
                        b.Write((float)m.FaceNormals[i].Y);
                        b.Write((float)m.FaceNormals[i].Z);

                        b.Write((float)pt1.X);
                        b.Write((float)pt1.Y);
                        b.Write((float)pt1.Z);

                        b.Write((float)pt2.X);
                        b.Write((float)pt2.Y);
                        b.Write((float)pt2.Z);

                        b.Write((float)pt3.X);
                        b.Write((float)pt3.Y);
                        b.Write((float)pt3.Z);

                        b.Write(AttributeByteCount);
                    }
                }
            }
        }

        public static void ExportBinary(string filePath, Mesh m)
        {
            //triangulate, compute face normals and count facets
            int faceCnt = 0;

            m.Faces.ConvertQuadsToTriangles();   // STL supports trinangles only!
            m.FaceNormals.ComputeFaceNormals();
            faceCnt += m.Faces.Count;

            // Use using statement and File.Open.
            using (BinaryWriter b = new BinaryWriter(
                File.Open(filePath, FileMode.Create)))
            {
                byte[] header = Encoding.ASCII.GetBytes("Binary STL generated by Eddy3D" + EddyLib.EddyVersion.ProductVersion);
                byte[] headerFull = new byte[80];
                Buffer.BlockCopy(header, 0, headerFull, 0, Math.Min(header.Length, headerFull.Length));

                b.Write(headerFull);
                b.Write((UInt32)faceCnt);

                UInt16 AttributeByteCount = 0; //After these follows a 2-byte ("short") unsigned integer that is the "attribute byte count" – in the standard format, this should be zero because most software does not understand anything else.

                for (int i = 0; i < m.Faces.Count; i++)
                {
                    var pt1 = m.Vertices[m.Faces[i].A];
                    var pt2 = m.Vertices[m.Faces[i].B];
                    var pt3 = m.Vertices[m.Faces[i].C];

                    b.Write((float)m.FaceNormals[i].X);
                    b.Write((float)m.FaceNormals[i].Y);
                    b.Write((float)m.FaceNormals[i].Z);

                    b.Write((float)pt1.X);
                    b.Write((float)pt1.Y);
                    b.Write((float)pt1.Z);

                    b.Write((float)pt2.X);
                    b.Write((float)pt2.Y);
                    b.Write((float)pt2.Z);

                    b.Write((float)pt3.X);
                    b.Write((float)pt3.Y);
                    b.Write((float)pt3.Z);

                    b.Write(AttributeByteCount);
                }
            }
        }

        //public static void ExportBinaryList(string filePath, List<Mesh> meshObjects, String filePrefix)
        //{
        //    //triangulate, compute face normals and count facets
        //    int faceCnt = 0;

        // foreach (GeometryBase m in meshObjects) { if (m.ObjectType ==
        // Rhino.DocObjects.ObjectType.Brep || m.ObjectType == Rhino.DocObjects.ObjectType.Extrusion
        // || m.ObjectType == Rhino.DocObjects.ObjectType.Surface) { Mesh obj = (Mesh)m; meshObjects.Add(obj);

        // foreach (Mesh mm in meshObjects) { mm.Faces.ConvertQuadsToTriangles(); // STL supports
        // trinangles only! mm.FaceNormals.ComputeFaceNormals(); faceCnt += mm.Faces.Count; } }

        // Mesh newMesh = (Mesh)m;

        // using (BinaryWriter b = new BinaryWriter(File.Open(filePath, FileMode.Create))) { byte[]
        // header = Encoding.ASCII.GetBytes("Binary STL generated by VirtualWindTunnel v0.1"); byte[]
        // headerFull = new byte[80]; Buffer.BlockCopy(header, 0, headerFull, 0,
        // Math.Min(header.Length, headerFull.Length));

        // b.Write(headerFull); b.Write((UInt32)faceCnt);

        // UInt16 AttributeByteCount = 0; //After these follows a 2-byte ("short") unsigned integer
        // that is the "attribute byte count" – in the standard format, this should be zero because
        // most software does not understand anything else.

        // for (int i = 0; i < 3; i++) { var pt1 = newMesh.Vertices[newMesh.Faces[i].A]; var pt2 =
        // newMesh.Vertices[newMesh.Faces[i].B]; var pt3 = newMesh.Vertices[newMesh.Faces[i].C];

        // b.Write((float)newMesh.FaceNormals[i].X); b.Write((float)newMesh.FaceNormals[i].Y); b.Write((float)newMesh.FaceNormals[i].Z);

        // b.Write((float)pt1.X); b.Write((float)pt1.Y); b.Write((float)pt1.Z);

        // b.Write((float)pt2.X); b.Write((float)pt2.Y); b.Write((float)pt2.Z);

        // b.Write((float)pt3.X); b.Write((float)pt3.Y); b.Write((float)pt3.Z);

        // b.Write(AttributeByteCount); }

        // }

        //    }
        //}
    }
}