; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Eddy"
#define MyAppVersion "0.2"
#define MyAppPublisher "Patrick Kastner, Timur Dogan"
#define MyAppURL "http://www.eddy3d.com"
#define MyAppExeName "Eddy"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9A556759-FCEE-44BA-B145-42EA1CBDAF5B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputDir={#MyAppVersion}
OutputBaseFilename=Eddy
Compression=lzma
SolidCompression=yes

[ISPP]
#define GrasshopperLib "{userappdata}\Grasshopper\Libraries"
#define OFInstallDir   "C:\OpenFOAM"

#include "USERESL.txt"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
#include "Eddy.txt"
#include "Gnuplot.txt"
   
[Code]

#include "GnuplotCode.txt"