; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Eddy"
#define MyAppVersion "0.2"
#define MyAppPublisher "Patrick Kastner, Timur Dogan"
#define MyAppURL "http://www.eddy3d.com"
#define MyAppExeName "Eddy"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9A556759-FCEE-44BA-B145-42EA1CBDAF5B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputDir=Installer{#MyAppVersion}
OutputBaseFilename=Eddy_BlueCFD
Compression=lzma
SolidCompression=yes

[ISPP]
#define GrasshopperLib "{userappdata}\Grasshopper\Libraries"
#define OFInstallDir   "C:\OpenFOAM"


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CallBatchRunner.exe"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CallOC.exe"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CallOF.exe"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CallProbes.exe"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CallRay.exe"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CommandLine.dll"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\ConsoleAppLauncher.dll"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\CsvHelper.dll"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\Eddy.gha"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\EddyLib.dll"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Documents\GitHub\WindTunnel\Eddy\bin\RhinoCommon.dll"; DestDir: "{#GrasshopperLib}"; Flags: ignoreversion
Source: "C:\Users\Patrick Kastner\Box Sync\PatrickESL\Eddy\blueCFD-Core-2017-2-win64-setup.exe"; DestDir: "{#OFInstallDir}"; AfterInstall: RunOtherInstaller
Source: "C:\OpenFOAM\*"; DestDir: "{#OFInstallDir}\"; Flags: ignoreversion recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Code]
procedure RunOtherInstaller;
var
  ResultCode: Integer;
begin
  if not Exec(ExpandConstant('{#OFInstallDir}\blueCFD-Core-2017-2-win64-setup.exe'), '', '', SW_SHOWNORMAL,
    ewWaitUntilTerminated, ResultCode)
  then
    MsgBox('Other installer failed to run!' + #13#10 +
      SysErrorMessage(ResultCode), mbError, MB_OK);
end;


