; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "Strings\Header.txt"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9A556759-FCEE-44BA-B145-42EA1CBDAF5B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputDir={#MyAppVersion}
OutputBaseFilename=Eddy_{#MyAppVersion}
Compression=lzma
SolidCompression=yes


[ISPP]
#define GrasshopperLib "{userappdata}\Grasshopper\Libraries"
#define OFInstallDir   "C:\OpenFOAM"
#define TemplatesDir "{%HOMEPATH}\Eddy\Templates\"

#include "Strings\USERESL.txt"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
#include "Strings\Eddy.txt"

   
[Code]

