name: Build Eddy3D

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore Eddy.sln

    - name: Build
      run: msbuild Eddy.sln /p:Configuration=Release /p:PreBuildEvent= /p:PostBuildEvent=


      # Tests currently don't work because of "Rhino system dir not found: C:\Program Files\Rhino 7\System"

#    - name: Setup VSTest and add to PATH
#      uses: darenm/Setup-VSTest@v1
#      id: setup_vstest
#
#    - name: Run VSTest
#      id: run_vstest
#      #working-directory: $\x64\Debug\
#      run: vstest.console.exe /Platform:x64 "RhinoPlugin.Test.Xunit\bin\x64\Debug\net472\RhinoPlugin.Test.Xunit.dll"
